"""add passport fields to employees

Revision ID: 761b8ddf3477
Revises: c296c58e437c
Create Date: 2026-06-26 09:09:09.667200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761b8ddf3477'
down_revision: Union[str, Sequence[str], None] = 'c296c58e437c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('document_type', sa.String(length=100), nullable=False))
    op.add_column('employees', sa.Column('id_series', sa.String(length=10), nullable=False))
    op.add_column('employees', sa.Column('id_number', sa.String(length=20), nullable=False))
    op.add_column('employees', sa.Column('id_date', sa.Date(), nullable=False))
    op.add_column('employees', sa.Column('id_issued_date', sa.String(length=255), nullable=False))
    op.add_column('employees', sa.Column('address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'id_issued_date')
    op.drop_column('employees', 'id_date')
    op.drop_column('employees', 'id_number')
    op.drop_column('employees', 'id_series')
    op.drop_column('employees', 'document_type')
    # ### end Alembic commands ###
