"""remove period from inventories

Revision ID: c296c58e437c
Revises: 01f6172e6997
Create Date: 2026-06-16 10:49:49.639726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c296c58e437c'
down_revision: Union[str, Sequence[str], None] = '01f6172e6997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('period', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
