"""rename id_date to id_issued_date, id_issued_date to issued_by

Revision ID: fc07e0ef7634
Revises: 761b8ddf3477
Create Date: 2026-06-26 10:03:46.313121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc07e0ef7634'
down_revision: Union[str, Sequence[str], None] = '761b8ddf3477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('issued_by', sa.String(length=255), nullable=False))
    op.alter_column('employees', 'id_issued_date',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Date(),
               postgresql_using='id_issued_date::date',
               existing_nullable=False)
    op.drop_column('employees', 'id_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('id_date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('employees', 'id_issued_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('employees', 'issued_by')
    # ### end Alembic commands ###
